### ISSUE TITLE
Wrong colors on sprites and flickering title bar

### ISSUE THREAD

**Issue by semiversus** [NJU-ProjectN/LiteNES#2]
Hi,

when I start LiteNES with Super Mario Bros I get wrong colors on some sprites and a flickering title bar. Is this the current state or do I make a mistake? If it's the current state I'm willing to help.

Regards
  Günther

**Comment by jiangyy** [comment]
Thanks! It's the current (buggy) state and I appreciate any improvement to it.

**Comment by semiversus** [comment]
I've worked with https://github.com/fogleman/nes and fceux. They have a pretty stable implementation of the PPU with a lot of corner cases I've found missing in your implementation. I'm not a big fan of major rewrites so I'll try to adapt the PPU step by step. From a architecture point of view it's the cleanest NES emulator I've found on the net so I'll try to extend it ;-)

**Comment by semiversus** [comment]
I missed giving credits to Stanislav Yaglo too

**Comment by jiangyy** [comment]
Wow! That are both great projects! I cloned Yaglo's code when I'm working on an operating system practicum course and the very first lab is to port this NES emulator into an x86 bare metal: that's why the focus is "least system dependency". With just registered interrupt handlers plus a function for drawing a pixel written by a student, the emulator works. I wasn't expecting it to run complicated games (as just a proof-of-concept project to let students practice with programming the bare metal), but it's quite cool for another people contributing to this project and make it better :)

I'm off the project for around two years, but it'll become active again -- I'll teach the course in the near future.

**Comment by semiversus** [comment]
Funny - I'm teacher too and want to use it in my course. See let's see forward to improve this project (which is already great).

**Comment by semiversus** [comment]
I was digging to get the source of the bug but wasn't successful yet.

Wrong colors in background: The problem seems to be somewhere in the rendering of the background (ppu_draw_background_scanline). I think the attribute table gets misaligned somehow. I've started to make a debugging environment to cross check ppu memory with fceux and see where the problem is.

Flickering title bar: split screen handling of ppu seems to have a problem. Cross checked with fogleman's go nes emulator and have some ideas for improvment.

**Comment by jdmoreira** [comment]
I'm also experiencing the same bugs 😢 

I've forked the project and ported hal.c to sdl2 since I wasn't interested in using Allegro.
My fork is at https://github.com/jdmoreira/LiteNES in case someone is interested.

I'm willing to fix the PPU bugs to a level where Super Mario Bros. plays without issues. It will probably take me a while since I don't understand how the hardware works yet. If someone else succeeds before me I would appreciate a pull request.

Keep up the good work! This emulator is awesome 👍

**Comment by GorgonMeducer** [comment]
I am recently porting this project to Cortex-M7 (ARM processors), it seems that there are plenty of issue in PPU. I have tried both Super-mario and Super Tank. The games' logic look good but the display always missing something. For example, you can not see the scrolling effects and tanks always miss the other half. 

Is this a know issue? Will it be fixed, or should I simply give up?
Many thanks.

**Comment by GorgonMeducer** [comment]
I have created an embedded version.
https://github.com/GorgonMeducer/EmbeddedNES

The code has been heavily optimised (rewritten) in order to shrink memory requirements. Performance are recently increased 6 times.

**Comment by jiangyy** [comment]
@GorgonMeducer They're known issues. We're now using another the binary of an optimized version of LiteNES (faster and much smaller memory footprint, but lots of messy code) in the course teaching and will not maintain this project anymore. We do planned a new NES project to have an optimized PPU and memory system, but we have lots of stuffs of higher priority to be done.

**Comment by GorgonMeducer** [comment]
@jiangyy Thank you for your explanation. I start a dedicated project (https://github.com/GorgonMeducer/EmbeddedNES) , try to optimise the liteNES and fix the PPU issue. You can take my project as a reference for your future work.

**Comment by ydb-beep** [comment]
@jiangyy
Hi everyone, I'm new to gitub, I think I find the wrong color bug. in file ppu.c line 156:
`bool left = (tile_x % 32 < 16);`
to fix:
`bool left = (tile_x % 4 < 2);`

**Comment by semiversus** [comment]
@ydb-beep Looking good. You could dive into github and see, how you could create a pull request with the fix. Otherwise, I'm sure @jiangyy will fix it right away.

**Comment by jiangyy** [comment]
@ydb-beep Since you haven't send a pull request for a couple days, I fixed it by myself. I also slightly modified the Makefile. Just wonder how did you found the bug?

**Comment by ydb-beep** [comment]
@jiangyy Sorry for the late reply. I havn't got a lot of time cause I'm in my forth year of university，while I have to re-learning a lot of  courses to avoid the fifth grade. I'm reveiwing LiteNES's code to learn how emulators work. The bug was found when I rewriting the code to shrink memory requirements. There is not a debug or trace skills, just knowing how PPU work and look at the code tells me the wrong line.Besides the Flickering title bar is still a bug. I may work  it later if I got some space. Best regards.

**Comment by jiangyy** [comment]
Thanks @ydb-beep! Reeeeeeeeeeeealy nice to see someone fix this!!!

This code is a port of [mynes](https://github.com/yaglo/mynes). I created a few pull requests on that. When you're contributing to other projects, consider a fork and pull-request!
